### ISSUE TITLE
Modify Roles to Support Ansible Runner

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipucords#1835]
## Feature description:

**playbook**
```
- name: example
  raw: echo "bar"
  register: foo
```

Ansible Runner currently only provides the `stdout` of raw commands. However, we process system information by associating the register name `foo` as a key and the `stdout` as the value e.g. `{'foo':'bar'}`.

In order for ansible runner to work with our current process we need to ensure that `raw` commands are captured through a `set_fact`. 

For example: 

```
- name: example
  raw: echo "bar"
  register: internal_foo

- name: set_foo_fact
  set_fact:
    foo: "{{internal_foo}}"
  ignore_errors: yes
```

The `set_fact` method will still provide us with the ability to obtain a key and value.
