### ISSUE TITLE
Get results directly from raw tasks

### ISSUE THREAD

**Issue by noahl** [quipucords/quipucords#369]
Right now, sonar's Ansible roles have a lot of instances of the same pattern:
```
  - name: gather internal_my_fact
    raw: gather-fact
    register: internal_my_fact

  - name: set my_fact
    set_fact:
        my_fact: "{{ internal_my_fact['stdout'] }}"
```

For every task where we do real work, we have another boilerplate task which turns that into a fact. I don't like this, because every boilerplate task is an opportunity to introduce a bug.

I think we can improve our reliability by getting fact information directly from the tasks that do the work. Right now we need the `set_fact` tasks because they tell us the name of the fact we are collecting, but I discovered in an example plugin (https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/foreman.py ) that we can use the `result._task` variable to get the same information.

In addition to increasing reliability, it will also be nice to lower the amount of boilerplate.
